# Generated by Selenium IDE
from django.contrib.staticfiles.testing import StaticLiveServerTestCase
from selenium import webdriver
from selenium.webdriver.common.by import By
import tempfile
from custom_user.models import CustomUser

class TestTestinterfazlogin(StaticLiveServerTestCase):

  def setUp(self):
    options = webdriver.ChromeOptions()
    options.add_argument("--no-sandbox")
    options.add_argument("--headless")
    options.add_argument("--disable-gpu")
    options.add_argument("--window-size=1936,1048")
    self.driver = webdriver.Chrome(options=options)
    self.user = CustomUser.objects.create_superuser(email='tesuser@example.com', password='user123')
    self.vars = {}

  def tearDown(self):
    super().tearDown()
    self.driver.quit()

  def test_interfaz_login(self):
    self.driver.get(self.live_server_url)
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("tesuser@example.com")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("user123")
    self.driver.find_element(By.CSS_SELECTOR, ".ui-button-primary:nth-child(4)").click()
    sidebar=self.driver.find_element(By.ID, "sidebar")
    self.assertTrue(sidebar.is_displayed())
  
  def test_interfazenviarsolicitud(self):
    self.driver.get(self.live_server_url)
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.LINK_TEXT, "Enviar solicitud").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(2) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(2) > input").send_keys("nombreTest")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > input:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > input:nth-child(1)").send_keys("apellidosTest")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4) > input:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4) > input:nth-child(2)").send_keys("emailTest@gmail.com")
    self.driver.find_element(By.NAME, "disponibilidad").click()
    self.driver.find_element(By.NAME, "disponibilidad").send_keys("preferenciasTest")
    self.driver.find_element(By.CSS_SELECTOR, "#solicitudForm p:nth-child(6) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "#solicitudForm p:nth-child(6) > input").send_keys("disponibilidadTest")
    self.driver.find_element(By.CSS_SELECTOR, ".ui-button:nth-child(7)").click()
